######################################################################
# Automatically generated by qmake (2.01a) Tue Dec 25 02:18:50 2012
######################################################################

QT += core gui

TEMPLATE = app
TARGET = qrandom
CONFIG += console
CONFIG -= app_bundle

# Input
SOURCES += main.cpp
